### ISSUE TITLE
Normalise font size to 16px

### ISSUE THREAD

**Issue by David-Klemenc** [elixir-lang/elixir-lang.github.com#1727]
I would like to change the base font size to 16px (as set in html css definition)

For some reason the body decreases it from 16px to 15.2px
```css
body {
  margin: 0;
  font: 0.95em/1.692307em 'Bitter', Georgia, 'Times New Roman', Times, serif;
  color: #24292e;
  padding: 0;
  height: 100%;
}
```
To keep it consistent the change would be:

```css
body {
  margin: 0;
  font: 1em/1.692307em 'Bitter', Georgia, 'Times New Roman', Times, serif;
  color: #24292e;
  padding: 0;
  height: 100%;
}
```

This would better follow accessibility guidelines for example [typography guidelines](https://accessibility.digital.gov/visual-design/typography/)

Because the Bitter font is set to a size != 1em the math (in the comments) in some of the css is incorrect (although I might just not understand it) for example:

```css
h1 { font-size: 2.5384615384615383em; }    /* 33 / 13 = 2.5384615384615383 */
```
But if we inspect a h1 tag we get this:
```
font-size: 38.584614px;
2.5384615384615383em h1
```
